name: 🚀 Deploy to Auto-update on push

on:
  push:
    branches:
      - auto-update

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Rename .htaccess (Before Upload)
        run: mv .htaccess htaccess.txt

      # Sync files via FTP
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_AUTO_UPDATE_USER }}
          password: ${{ secrets.FTP_AUTO_UPDATE_PASSWORD }}
          dangerous-clean-slate: true
          timeout: 10800000 # 3 hours
          exclude: |
              **/.git*
              **/.github*
              **/node_modules*
              htaccess.txt
