name: 🚀 Deploy to Staging on push

on:
  push:
    branches:
      - staging

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Sync files via FTP
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_STAGING_USER }}
          password: ${{ secrets.FTP_STAGING_PASSWORD }}
          dangerous-clean-slate: false
          timeout: 10800000 # 3 hours
